#include "TipReferenceData.h"

namespace TipReferenceData {
const std::vector<TipReferenceSection>& sections() {
  static const std::vector<TipReferenceSection> kSections = {
      {"AS I GO",
       {{"Assess", "Lie, yardage, wind, hazards, slope, and what is working today."},
        {"Select", "Choose club, target, shot shape and trajectory. Commit before stepping in."},
        {"Imagine", "Picture ball flight, landing spot, rollout, rhythm and tempo."},
        {"Go", "Step in, trust the decision and swing without second-guessing."},
        {"Own It", "Accept the result, learn if needed, then move on."}}},
      {"SUB-5 RULES",
       {{"No doubles", "Take your medicine. Recovery speed matters more than perfection."},
        {"No three-putts", "Distance control first, then short-putt focus."},
        {"No penalties", "Ball in play beats bomb-and-pray."},
        {"Boring golf wins", "Fairway, fat side, two-putt."},
        {"One cue", "Eyes on impact, not mechanics. Do not tinker mid-round."},
        {"Club up", "Swing about 85 percent instead of forcing a full rip."},
        {"Never miss twice", "After a missed green, get the next shot on the surface or into kick-in range."}}},
      {"COURSE MANAGEMENT",
       {{"Off the tee", "Playable beats perfect. Downshift when driver brings penalty into play."},
        {"Take one side out", "Set alignment and face so the big miss cannot find trouble."},
        {"Approach", "Middle is magic. Favor the safest side and avoid the short-side miss."},
        {"Control", "A three-quarter club is often better than a full rip."},
        {"Recovery", "No hero shots you do not practice. Punch back to a useful number."},
        {"Par 5", "When the green is guarded, wedge-wedge can beat fairway-wood into trouble."}}},
      {"DRILLS",
       {{"Circle Drill", "5-8 balls around 3 feet. Make all in a row, then expand to 4-5 feet."},
        {"Landing Zone", "Land chips and pitches on a towel or marked zone, then vary rollout."},
        {"Random Yardage", "Change target distance every ball and commit to a fresh plan each time."},
        {"Fairway Finder", "Hit controlled half or three-quarter shots into a defined fairway."},
        {"Tee Box Pressure", "One ball, full routine, imagined pressure. Hit it, then step away."},
        {"Punch-Out Path", "Practice low controlled shots under or around an obstacle."},
        {"Dollar Bill", "Draw a dollar-bill-sized box in sand and splash the box, not the ball."},
        {"Think / Play Box", "Plan and visualize behind the ball; once you step in, commit and swing."}}},
      {"WEDGE MATRIX",
       {{"PW", "Example: 7:30 = 90 | 9:00 = 105 | 10:30 = 120"},
        {"50 deg", "Example: 7:30 = 80 | 9:00 = 95 | 10:30 = 110"},
        {"54 deg", "Example: 7:30 = 70 | 9:00 = 85 | 10:30 = 100"},
        {"58 deg", "Example: 7:30 = 55 | 9:00 = 70 | 10:30 = 85"},
        {"Purpose", "Build your own 30-120 yard matrix using repeatable 7:30, 9:00 and 10:30 swings."}}},
      {"EQUIPMENT",
       {{"Ball", "Pick a model and stay with it for consistent spin and feel."},
        {"Driver", "Use loft and shaft you can keep in play. A fairway finder is a real club choice."},
        {"Wedges", "Target 4-degree gaps, check loft/lie twice yearly, and maintain a wedge matrix."},
        {"Putter", "Fit lie and loft; train face control inside 10 feet."},
        {"Irons", "Check loft and lie twice yearly."},
        {"Grips", "Replace annually or when shiny or slick."}}},
      {"TROUBLESHOOT",
       {{"Two-way tee miss", "Narrow stance, tee lower, slightly stronger grip, three-quarter tempo, widest side."},
        {"Pull / over-draw", "Ball slightly back, align to right edge of safe zone, feel a hold-off finish."},
        {"Block / fade", "Ball a fraction forward, feel lead wrist cover, commit to a draw start line."},
        {"Fat / thin", "Choke down, 80 percent tempo, brush the grass after the ball."},
        {"Greenside fear", "Use one stock chip, land it on a zone, accept 10-15 feet and roll the putt."},
        {"Reset", "Exhale, soften jaw and forearms, then say: Next shot only."}}},
      {"WARM UP",
       {{"1:00", "Cat-Camel"},
        {"2:00", "Thoracic openers"},
        {"3:00", "Hip hinges"},
        {"4:00", "Split-squat pulses"},
        {"5:00", "Band pull-aparts"},
        {"6:00", "Torso turns"},
        {"Finish", "2 x 10 air swings, half to three-quarter."}}},
  };
  return kSections;
}
}  // namespace TipReferenceData
